name: yournoteapp
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # StateNotifier
  state_notifier:
  flutter_state_notifier:
  analyzer:
  provider:
  freezed_annotation:

  # Firebase
  firebase_core:
  firebase_auth:
  firebase_analytics:
  cloud_firestore:
  firebase_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  freezed:
  pedantic_mono:
  flutter_native_splash:

flutter:
  uses-material-design: true
  assets:
    - assets/images/


flutter_native_splash:
  image: "assets/images/splash_icon.png"
  color: "47B0D1"